### ISSUE TITLE
Warnings on Load / Character Floats Above Ground Sometimes

### ISSUE THREAD

**Issue by valkyrienyanko** [thomasaedk/unity-rpg#1]
## Popup Warnings
These warnings pop up when I open the project.

![image](https://user-images.githubusercontent.com/6277739/120431420-143f1800-c33e-11eb-9c4e-30dabc427b16.png)

## Character Floats Above Ground Sometimes
Sometimes the character floats above the terrain when walking around? It's like there are invisible bumps on the ground making the character shoot up a bit.

**Comment by thomasaedk** [comment]
Thank you @valkyrienyanko.
I have noticed these warnings and that the movement/animation needs some tweaking. 
I'm developing this game by following a [course on Udemy](https://www.udemy.com/course/unityrpg/). 

These warnings and the movement/animation will be fixed in a later commit.

As for the player floating above ground: I haven't tweaked the NavMesh nor the NavMeshAgent yet, but I hope that will fix the problem.
